// Generated by CoffeeScript 1.6.3
(function() {
  describe("Raffler namespace", function() {
    return it("should be defined", function() {
      return expect(Raffler).toBeDefined();
    });
  });

  describe("Raffler init", function() {
    return it("should exist", function() {
      return expect(Raffler.init).toBeDefined();
    });
  });

  describe("Entry Model", function() {
    it("should exist", function() {
      return expect(Raffler.Models.Entry).toBeDefined();
    });
    return describe("Attributes", function() {
      var entry;
      entry = new Raffler.Models.Entry;
      return it("should have default attributes", function() {
        expect(entry.attributes.name).toBeDefined();
        return expect(entry.attributes.winner).toBeDefined();
      });
    });
  });

  describe("Entries collection", function() {
    var entries;
    entries = new Raffler.Collections.Entries;
    it("should exist", function() {
      return expect(Raffler.Collections.Entries).toBeDefined();
    });
    it("should use the Restaurant model", function() {
      return expect(entries.model).toEqual(Raffler.Models.Entry);
    });
    return it("should use the localStorage", function() {
      return expect(entries.localStorage).toBeDefined();
    });
  });

  describe("Entries Routers", function() {
    return it("should be defined", function() {
      return expect(Raffler.Routers.Entries).toBeDefined();
    });
  });

}).call(this);
